### ISSUE TITLE
Generated Factory does not have the return type and lint cries

### ISSUE THREAD

**Issue by danielgomezrico** [charafau/json2builtvalue#12]
# Current
The generated factories do not have the `void` type on the return and then linter may warn about it

How it currently generates factories:
```dart
factory UserContext([Function(UserContextBuilder b) updates]) = _$UserContext;
```

Linter:
<img width="973" alt="image" src="https://github.com/charafau/json2builtvalue/assets/76348/51d32788-0308-476c-a147-3eea36ac01cd">

It looks to me that this becomes important after dart 2, since the type inference is stronger.

This is related to:
- https://github.com/dart-lang/sdk/issues/33749

# Expected
The generated factory has the void already there

```dart
factory UserContext([void Function(UserContextBuilder b) updates]) = _$UserContext;
```

**Comment by charafau** [comment]
thanks for creating the issue! This project is just a quick hack for creating classes for json, I don't really maintain it. 
Given current state of thing, I'll probably deprecate this when macros are available in dart.
