### ISSUE TITLE
Getters must be declared without a parameter list.

### ISSUE THREAD

**Issue by MichalTorma** [charafau/json2builtvalue#4]
First of all thanks for the tool. It's awesome.

 I found a problem when parsing keys with a parameter list. Could this be handled by some regex in generated key names perhaps? 
input example:
`{"Shape.STArea()": "Shape.STArea()"}`
output:

```
Error: Could not format because the source could not be parsed:

line 14, column 68: Getters must be declared without a parameter list.
@BuiltValueField(wireName: 'Shape.STArea()') String get shapeSTArea();
                                                                   ^
```

I can work around it of course - it would just be nice 😄

**Comment by MichalTorma** [comment]
I've just realized that this is build_value's fault. 
You can close the issue

**Comment by charafau** [comment]
Thanks for issue anyway!
