### ISSUE TITLE
Undefined name 'serializers'

### ISSUE THREAD

**Issue by datvtwkm** [charafau/json2builtvalue#5]
I meet this error! And I don't know how to solve this! It's clear that the variable 'serializers' are not declared!
![image](https://user-images.githubusercontent.com/29540449/46189325-49d30e00-c318-11e8-88bb-0983aa87675b.png)

**Comment by charafau** [comment]
Hello @datvtwkm, thank you for commenting. I think I should link some example and link to documentation, take a look at this serializer file:

https://github.com/charafau/todo_list/blob/master/lib/model/serializers.dart

and read post about serialization in built_value:

https://medium.com/dartlang/darts-built-value-for-serialization-f5db9d0f4159

**Comment by datvtwkm** [comment]
Thanks, I made it!
