### ISSUE TITLE
deserialize double value sometimes return to int type

### ISSUE THREAD

**Issue by datvtwkm** [charafau/json2builtvalue#6]
I want to deserialize an json string:
{
  "value" : 1.0
}

after transform by the tool from that string to the class, the property I receive is 
@BuiltValueField(wireName: 'value')
  int get value;
but the correct property must be
@BuiltValueField(wireName: 'value')
  double get value;

in this case, the function will stop in this line:
case 'value':
          result.value = serializers.deserialize(value,
              specifiedType: const FullType(String)) as String;
          break;
in myclass.g.dart file

**Comment by datvtwkm** [comment]
However, if the string is:
{
"value" : 1.5
}
then the property will be
@BuiltValueField(wireName: 'value')
double get value;
which the code runs smoothly

**Comment by datvtwkm** [comment]
my pubspecs:

dependencies:
  built_value: ^6.1.4
  built_collection: ^4.0.0

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4

**Comment by datvtwkm** [comment]
my current solution is to replace all '.0,' to ',' in response.body, like this
final String res = response.body.replaceAll('.0,', ',');

**Comment by charafau** [comment]
hi, thanks for reporting this. I'm afraid that I cannot do anything about how this is getting serialized this is all done by 3rd party library
